x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=
    - AIRFLOW__CORE__FERNET_KEY=
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW_INSTANCE_NAME=airflow-lead
    - AIRFLOW__WEBSERVER__INSTANCE_NAME=Airflow - Lead
   
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=eu-west-3
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/opt/airflow/requirements.txt
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    container_name: airflow-lead-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: airflow-lead-init
    entrypoint: /bin/bash
    command: >
      -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt &&
          airflow db init &&
          airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"

  webserver:
    <<: *airflow-common
    container_name: airflow-lead-webserver
    command: bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow webserver"
    ports:
      - "8086:8080"
    restart: always

  scheduler:
    <<: *airflow-common
    container_name: airflow-lead-scheduler
    command: bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow scheduler"
    restart: always

volumes:
  postgres_data:
